on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

      - run: dotnet new console

      - run: dotnet pack -p:RepositoryUrl=https://github.com/${{ dotnet.repository }} -p:Version=1.0.0

      - run: dotnet nuget push bin/Debug/*.pkg
